Projet0Django/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app0/', include(('app0.urls' , 'app0') ,namespace='app0')),
    path('login/', include('login_user.urls' )),

]

app0/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from login_user.views import user_logout


urlpatterns = [
     path('',views.index1, name='index1'),
     path('users', views.users),
     # path('ind', views.ind),
     path('list', views.list, name='list'),
     url(r'^(?P<user_id>[0-9]+)/$', views.detail_element, name='detail_name'),
     path('delete/<int:user_id>/', views.delete, name='delete'),
     path('edit/<int:user_id>/', views.edit, name='edit'),
     url(r'^ajouter/$', views.ajouter, name='ajouter'),
     path('search/', views.search, name='search'),
     path('work/', views.work, name='work'),

   
     
]

login_user/urls.py
from django.urls import path
from . import views
from login_user.views import home
urlpatterns = [
    
    path('login',views.user_login, name='login'),       
    path('index',views.index, name='index'),
    path("", home, name="homepage"),
    path("",views.user_logout, name='logout'),
    
]

app0/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=300)
    carNumber=models.CharField(max_length=200,null=False,unique=True)
    CIN=models.CharField(max_length=8)
    phone= models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)
 

 
 

login_user/models.py
from django.db import models

# Create your models here.

app0/forms.py
from django import forms



class UserForm(forms.Form):

        name = forms.CharField(
        label='Name',
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )
        
        carNumber= forms.CharField(
        label='CarNumber',
        max_length=8,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )



        cin= forms.CharField(
        label='CIN',
        max_length=8,
        min_length=8,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),

        )
        phone = forms.CharField(
        label='Name',
        max_length=12,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )

        fields = "__all__"

app0/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from datetime import datetime
from .models import User
from django.template import loader
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import UserForm
from django.views.generic.edit import DeleteView
from .forms import UserForm
from django.views.generic import TemplateView, ListView
from django.db.models import Q

def index1(request):
    users = User.objects.all()
    template = loader.get_template('app0/index1.html')
    context = {
        'users': users
    }
    return HttpResponse(template.render(context, request=request))


def detail_element(request,user_id):
    user = User.objects.get(pk=user_id)
    context = {
        'user_id':user.id ,
         'user_name':user.name,
         'user_number': user.carNumber,
         'created':user.created_at,
         'phone':user.phone
    }
    return render(request, 'app0/det.html', context)


def delete(request, user_id ,template_name='app0/confirm_delete.html'):
    user= get_object_or_404(User, pk=user_id)   
    if request.method=='POST' and 'yes' in request.POST:
        user.delete()
        return HttpResponseRedirect('/app0/')
    if request.method=='POST' and 'no' in request.POST:
        return HttpResponseRedirect('/app0/')       
    context = {
        'user_id':user.id ,
        'user_name':user.name,
    }
    return render(request, template_name, { 'user_name':user.name},)




def edit(request,user_id, template_name='app0/edit.html'):
    user= get_object_or_404(User,pk=user_id)
    form = UserForm(request.POST or None, user)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/app0/')
       
    return render(request, template_name, {'form':form})





def ajouter(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            carNumber = request.POST.get('carNumber')
            user = User.objects.filter(carNumber=carNumber)
            if not user.exists():
                user =User.objects.create(
                     name=name,
                     carNumber= carNumber
                                     )
            messages.success(request,'successfully!')
            return HttpResponseRedirect('/app0/')
        else:
            context = {
               'form': form
             }
            return HttpResponseRedirect('/app0/')
    else:
        form = UserForm()
        context['form'] = form  
    return render(request, 'app0/add.html',context)



def search(request):
    if request.method=='GET':
        search = request.GET.get('s')
        users=User.objects.all().filter(name=search)
        # return HttpResponseRedirect('app0/work.html')
        return render(request, 'app0/list.html' , {'users':users} )        


# def delete(request, user_id ,template_name='app0/confirm_delete.html'):
#     user= get_object_or_404(User, pk=user_id)   
#     if request.method=='POST' and 'yes' in request.POST:
#         user.delete()
#         return HttpResponseRedirect('/app0/')
#     if request.method=='POST' and 'no' in request.POST:
#         return HttpResponseRedirect('/app0/')       
#     context = {
#         'user_id':user.id ,
#         'user_name':user.name,
#     }
#     return render(request, template_name, { 'user_name':user.name},)
# 

# def index1(request):
#     return render(request, 'app0/index1.html')
def users(request):
    return render(request, 'users.html')
def list(request):
    return render(request, 'app0/list.html')

def work(request):
    return render(request, 'app0/work.html')

  

login_user/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth import authenticate,login
from django.contrib import messages
from django.template.loader import select_template


def home(request):
    """Home page."""
    return render(request, "home.html")
def index(request):
    return render(request, "index.html")
def user_login(request):
    """Authenticate a user."""
    # Etape 1 :
    username = request.POST["username"]
    password = request.POST["password"]

    # Etape 2 :
    user = authenticate(username=username, password=password)

    # Etape 3 :
    if user is not None:
        login(request,user)
        messages.add_message(request, messages.SUCCESS, "Vous êtes connecté !")
        return redirect("/app0/")
    else:
        messages.add_message(request, messages.ERROR, "Les champs renseignés sont invalides.")
        return redirect("homepage")
   


def user_logout(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS, "Vous êtes déconnecté !")
    return redirect("home")

app0/templates/app0/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="../../static/form/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="../../static/form/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="../../static/form/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="../../static/form/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">
    <link href="../../static/form/css/main.css" rel="stylesheet" media="all">
</head>
<body>
            <div class="card-heading">
                <h2 class="title"> Add User</h2>
            </div>
            <div class="card-body">
                <form action="{% url 'app0:ajouter'  %}" method="POST">
                  {% csrf_token %}
                <!-- *************************************** -->



                  <div class="form-row m-b-55">
                    <div class="name" for="{{ form.name.id_for_label }}">Name</div>
                    <div class="value">
                        <div class="row row-refine">
                            <div class="col-9">
                                <div class="input-group-desc">
                                    <input class="input--style-5" type="text" name="name" placeholder="your name">
                                    <label class="label--desc"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>





                    <!-- ****************************************** -->


                  <div class="form-row m-b-55">
                    <div class="name" for="{{ form.cin.id_for_label }}">CIN</div>
                    <div class="value">
                        <div class="row row-refine">
                            <div class="col-9">
                                <div class="input-group-desc">
                                    <input class="input--style-5" type="text" name="cin" placeholder="********">
                                    <label class="label--desc"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>





                <!-- ************************************* -->
                  <div class="form-row m-b-55">
                    <div class="name" for="{{ form.carNumber.id_for_label }}">Car Number</div>
                    <div class="value">
                        <div class="row row-refine">
                            <div class="col-9">
                                <div class="input-group-desc">
                                    <input class="input--style-5" type="text"  name="carNumber" placeholder="Max 8 chars" >
                                    <label class="label--desc"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
                <!-- ************************************ -->
                
                    <div class="form-row m-b-55">
                        <div class="name" for="{{ form.phone.id_for_label }}">Phone</div>
                        <div class="value">
                            <div class="row row-refine">
                                <div class="col-9">
                                    <div class="input-group-desc">
                                        <input class="input--style-5" type="text" name="phone" placeholder="+216">
                                        <!-- <label class="label--desc">Phone Number</label> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            <!-- ************************************** -->
                    <div>
                        <button class="btn btn--radius-2 btn--red" type="submit">Add</button>   
                    </div>
                </form>

 <!-- ************* -->
 {% if errors %}
  <div>
    {% for key, error in errors %}
    {% autoescape off %}
      {{ error }}
    {% endautoescape %}
    {% endfor %}
  </div>
  {% endif %}
<!-- ********* -->
            </div>
</body>
</html>

app0/templates/app0/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
    {% include 'app0/head.html' %} 
<body>


    <div id="tm-bg"></div>
    <div id="tm-wrap">
        <div class="tm-main-content">
            <div class="container tm-site-header-container">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-6 col-md-col-xl-6 mb-md-0 mb-sm-4 mb-4 tm-site-header-col">
                        <div class="tm-site-header">
                            <!-- **** -->
                            <div class="container">
                                <div class="row"></div>
                                <br/>
                                <div class="row">
                                <div class="col-md-2 col-xs-2 col-sm-2"></div>
                                    <div class="col-md-10 col-xs-10 col-sm-10">


                                        <div class="grid__item" id="home-link">
                                            <div class="product">
                                               
                
                                                 <div class="product__description">
                                                  
                                                  
                                                    {{ user_id}} <br>
                                                    {{ user_name}} <br>
                                                    {{ user_number}} <br>
                                                    {{ created}} <br>
                                                    
                                                 </div> 
                
                
                                            </div>
                                        </div>

                                        <form method="post" >
                                            {% csrf_token %}
                                          <div class="form-row">
                                            <div class="alert alert-warning">
                                                Are you sure you want to delete {{ user_name}} ?
                                            </div>
                                          </div>


                                          <button type="submit" class="btn btn-danger" name="yes">
                                              <span class="glyphicon glyphicon-trash"> yes</span>
                                          </button>

                                          <button type="submit" class="btn btn-primary btn-xs"  name="no" >
                                            <span class="glyphicon glyphicon-trash"> No</span>
                                         </button>


                                        </form>
                                    </div>
                                </div>
                                </div>
                            <!-- ****** -->



                        </div>                        
                    </div>
                </div>                
            </div>
            <!-- ********** -->
            <footer>
                <p class="small tm-copyright-text">Copyright &copy; <span class="tm-current-year">2018</span> Molka&Iheb
                
                    </p>
            </footer>
            <!-- *************** -->
        </div> 
    </div>
    <!-- load JS -->
    <script src="../static/app0/js/jquery-3.2.1.slim.min.js"></script>      
    <script src="../static/app0/slick/slick.min.js"></script>                  
    <script src="../static/app0/js/anime.min.js"></script>                     
    <script src="../static/app0/js/main.js"></script>  
    <script>      
        function setupFooter() {
            var pageHeight = $('.tm-site-header-container').height() + $('footer').height() + 100;

            var main = $('.tm-main-content');

            if($(window).height() < pageHeight) {
                main.addClass('tm-footer-relative');
            }
            else {
                main.removeClass('tm-footer-relative');   
            }
        }
        /* DOM is ready
        ------------------------------------------------*/
        $(function(){

            setupFooter();

            $(window).resize(function(){
                setupFooter();
            });

            $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright           
        });

    </script>             

</body>
</html>

app0/templates/app0/det.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{% static 'app0/img/icon.png' %}" />
        <title>SmartParking</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300">
        <link rel="stylesheet" href="{% static 'app0/css/bootstrap.min.css' %}">   
    
        <link rel="stylesheet" href="{% static 'app0/fontawesome/css/fontawesome-all.min.css' %}">     
        
        
        <link rel="stylesheet" type="text/css"  href="{% static 'app0/slick/slick.css' %}"/>
        
        <link rel="stylesheet" type="text/css"  href="{% static 'app0/slick/slick-theme.css' %}"/>
    
    
    
        <link rel="stylesheet"  href="{% static 'app0/css/styly.css' %}"> 
    
    
    
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script>document.documentElement.className="js";var supportsCssVars=function(){var e,t=document.createElement("style");return t.innerHTML="root: { --tmp-var: bold; }",document.head.appendChild(t),e=!!(window.CSS&&window.CSS.supports&&window.CSS.supports("font-weight","var(--tmp-var)")),t.parentNode.removeChild(t),e};supportsCssVars()||alert("Please view this in a modern browser such as latest version of Chrome or Microsoft Edge.");</script>
        
        <link  href="{% static 'app0/font-awesome/css/font-awesome2.css' %}" rel="stylesheet" />
    
    </head>
<body>

    <div id="tm-bg"></div>
    <div id="tm-wrap">
        <div class="tm-main-content">
            <div class="container tm-site-header-container">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-6 col-md-col-xl-6 mb-md-0 mb-sm-4 mb-4 tm-site-header-col">

                        <div class="grid__item" id="home-link">
                            <div class="product">
                               

                                 <div class="product__description">

                                    <a href="{% url 'app0:index1' %}">
                                    <button class="btn-xs">
                                        <i class="fa fa-backward" aria-hidden="true"></i>
                                    </button>
                                    </a>
                                     <p class="date">{{ created}} </p>

                                    <br>

                                   <div class="molka">
                                    <h4> Name: </h4>  {{ user_name}} 
                                    <h4> Car Number:</h4> {{ user_number}} 
                                    
                                    <h4>Phone number :</h4>  {{ phone}} 

                                    
                                </div>


                                 </div> 


                            </div>
                        </div>
                    </div>
                </div>                
            </div>

            
            <!-- ********** -->
            <footer>
                <p class="small tm-copyright-text">Copyright &copy; <span class="tm-current-year">2018</span> Molka&Iheb
                
                    </p>
            </footer>
            <!-- *************** -->
        </div> 
    </div>
    <!-- load JS -->
    <script src="../static/app0/js/jquery-3.2.1.slim.min.js"></script>      
    <script src="../static/app0/slick/slick.min.js"></script>                  
    <script src="../static/app0/js/anime.min.js"></script>                     
    <script src="../static/app0/js/main.js"></script>  
    <script>      
        function setupFooter() {
            var pageHeight = $('.tm-site-header-container').height() + $('footer').height() + 100;

            var main = $('.tm-main-content');

            if($(window).height() < pageHeight) {
                main.addClass('tm-footer-relative');
            }
            else {
                main.removeClass('tm-footer-relative');   
            }
        }
        /* DOM is ready
        ------------------------------------------------*/
        $(function(){

            setupFooter();

            $(window).resize(function(){
                setupFooter();
            });

            $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright           
        });

    </script>             

</body>
</html>

app0/templates/app0/index1.html
<!DOCTYPE html>
<html lang="en">
    {% include 'app0/headapp.html' %} 
<body>

    
{% if user.is_authenticated %}
<p class="welcome"> Welcome, {{ user.get_username }}. Thanks for logging in.</p>
{% else %}
<p class="welcome">Welcome, new user. Please log in.</p>
{% endif %}


<li class="nav-item text-white">
    {% if request.user.is_authenticated %}
       <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
    {% endif %}
</li>


    <div class="grid__item" id="home-link">
        {% include 'app0/message.html' %} 
    </div>

    <div id="tm-bg"></div>
    <div id="tm-wrap">
        <div class="tm-main-content">
            <div class="container tm-site-header-container">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-6 col-md-col-xl-6 mb-md-0 mb-sm-4 mb-4 tm-site-header-col">
                        <div class="tm-site-header">
                            <h1 class="mb-4">Smart Parking</h1>
                            <img src="../static/app0/img/underline.png" class="img-fluid mb-4">
                            <p> </p>        
                        </div>                        
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="content">
                            <div class="grid">
                               <!--  -->
                                <div class="grid__item" id="home-link">
                                    <div class="product">
                                        <div class="tm-nav-link">
                                            <i class="fas fa-home fa-3x tm-nav-icon"></i>
                                            <span class="tm-nav-text">List</span>
                                            <div class="product__bg"></div>   
                                        </div>  
                                         <div class="product__description">
                                            {% include 'app0/list.html' %}    
                                         </div> 
                                    </div>
                                </div>
                        <!--  -->
                                <div class="grid__item" id="home-link">
                                    <div class="product">
                                        <div class="tm-nav-link">
                                            <i class="fa fa-plus fa-3x tm-nav-icon"></i>
                                            <span class="tm-nav-text">Add</span>
                                            <div class="product__bg"></div>   
                                        </div>  

                                         <div class="product__description">
                                            {% include 'app0/add.html' %} 
                                         </div> 
                                    </div>
                                    </a>  
                                </div>
                         <!--  -->
                         <a href="{% url 'app0:index1' %}">
                         <div class="grid__item" id="home-link">
                   
                            <div class="product">
                                <div class="tm-nav-link">
                                    <i class="fas fa-handshake fa-3x tm-nav-icon"></i>
                                    <span class="tm-nav-text">Work</span>
                                    <div class="product__bg"></div>   
                                </div>  
                                
                                 <div class="product__description">
                                    {% include 'app0/work.html' %} 
                                 </div>
                            </div>
                       

                          </div>
                        </a>
                                <!-- -------------- -->
                                <div class="grid__item" id="home-link">
                                    <div class="product">
                                        <div class="tm-nav-link">
                                            <i class="fas fa-comments fa-3x tm-nav-icon"></i>
                                            <span class="tm-nav-text">Contact</span>
                                            <div class="product__bg"></div>   
                                        </div>  
                                        <div class="product__description">
                                        {% include 'app0/contact.html' %} 
                                        </div> 
                                    </div>  
                                </div>
                                <!--*****************  -->
                            </div> 
                        </div>                       
                    </div>
                </div>                
            </div>
            <!-- ********** -->
            <footer>
                <p class="small tm-copyright-text">Copyright &copy; <span class="tm-current-year">2018</span> Molka&Iheb
                
                    </p>
            </footer>
            <!-- *************** -->
        </div> 
    </div>
    <!-- load JS -->
    <script src="../static/app0/js/jquery-3.2.1.slim.min.js"></script>      
    <script src="../static/app0/slick/slick.min.js"></script>                  
    <script src="../static/app0/js/anime.min.js"></script>                     
    <script src="../static/app0/js/main.js"></script>  
    <script>      
        function setupFooter() {
            var pageHeight = $('.tm-site-header-container').height() + $('footer').height() + 100;

            var main = $('.tm-main-content');

            if($(window).height() < pageHeight) {
                main.addClass('tm-footer-relative');
            }
            else {
                main.removeClass('tm-footer-relative');   
            }
        }
        /* DOM is ready
        ------------------------------------------------*/
        $(function(){

            setupFooter();

            $(window).resize(function(){
                setupFooter();
            });

            $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright           
        });

    </script>             

</body>
</html>

app0/templates/app0/list.html
{% block detail %}
          <div class="row">
              <section class="wrapper">
                  <div class="row mt">
                    <div class="col-md-12">
                      <div class="content-panel">
                        <table class="table table-striped table-advance table-hover">
                          <h4><i class="fa fa-angle-right"></i> Cars Lists</h4>


                          {% include 'app0/search_form.html' %} 

                          
                          <hr>



                          <thead>
                            <tr>
                              <th><i class="fa fa-bullhorn"></i> Name</th>
                              <th class="hidden-phone"><i class="fa fa-car" aria-hidden="true"></i> Car number</th>
                              <th><i class="fa fa-bookmark"></i> Created</th>
                              <!-- <th><i class=" fa fa-edit"></i> Status</th> -->
                              <th></th>
                            </tr>
                          </thead>
                          <tbody>  
                            {% for user in users %}   
                            <tr> 
                           
                              <td>
                                <a href="{% url 'app0:detail_name' user_id=user.id %}">{{user.name}} </a>
                              </td >
                              <td class="hidden-phone">{{ user.carNumber}}</td >
                              <td>{{ user.created_at }} </td>
                              <td><span class="label label-info label-mini"></span></td>
                              <td>

                                <a href="{% url 'app0:edit' user_id=user.id %}">
                                <!-- <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button> -->
                                <button class="btn btn-primary btn-xs" type="submit"><i class="fa fa-pencil"></i></button>
                                </a>

                                <a href="{% url 'app0:delete' user_id=user.id %}">
                                <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
                                </a>




                              </td>
              
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>

                      </div>
                      <!-- /content-panel -->
                    </div>
                    <!-- /col-md-12 -->
                  </div>
                  <!-- /row -->
                </section>
          </div>
          
{% endblock %}  

app0/templates/app0/message.html
{% for message in messages %}


  <div class="alert {{ message.tags }} alert-dismissible" role="alert">

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">

              <span aria-hidden="true">&times;</span>
 
            </button> 
            




            <!-- <button type="button"  > &times;  </button> -->
             <!-- <span aria-hidden="true">  </span> -->
            <!-- <a href="../app0/index1"> &times; </a>  -->


      {{ message }}

    

  </div>
{% endfor %}

app0/templates/app0/search_form.html
<form class="form-inline my-2 my-lg-0" action="{% url 'app0:search' %}"  method="GET">
  <input class="form-control mr-sm-2" type="search"   placeholder="Search" aria-label="Search" name="s">
  <!-- <a href="{% url 'app0:search' %}"> -->
    <button class="btn btn--radius-2 btn--red" type="submit">Add</button>   
  <!-- </a> -->

  <!-- <input type="submit" value="ok"> -->
</form>

app0/templates/app0/work.html
<p> our Work </p>

login_user/templates/home.html
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>SmartParking</title>
  <link rel="icon" type="image/png" href="../static/login_user/img/icon.png" />
  <link rel="stylesheet" href="../static/login_user/css/style.css">
</head>
<body>
    {% include 'login.html' %}
</body>
</html>